import '../styles/globals.css'
import Header from './Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Next 13 Site</title>
      </head>
      <body>
        <Header />
        {children}
        </body>
    </html>
  )
}
